modLoader = "javafml"
loaderVersion = "[44,)"
issueTrackerURL = "https://github.com/TimStewartJ/TheMightyArchitectury/issues"
license = "MIT"

[[mods]]
modId = "mightyarchitect"
version = "${version}"
displayName = "The Mighty Architect"
authors = "simibubi, timmie, victor"
description = '''
Architectury port of The Mighty Architect. Design elaborate buildings within a minute!
'''
#logoFile = ""

[[dependencies.mightyarchitect]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mightyarchitect]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mightyarchitect]]
modId = "architectury"
mandatory = true
versionRange = "[4.5.75,)"
ordering = "AFTER"
side = "BOTH"